### ISSUE TITLE
Plugin  DashToSpaceInChannelName floods console with these errors when enabled. 

### ISSUE THREAD

**Issue by ItMeSarah** [Niemiets/BD_Plugins#1]
![image](https://user-images.githubusercontent.com/67713330/120622707-acafc800-c424-11eb-92bc-4e3c99220549.png)
 Floods the console with these errors every time you change channels, it changes the channel name to remove the dash  but floods the console.  (You also have to change servers upon first start of plugin)

**Comment by lolpowerluke** [comment]
the dash doesnt disapear either

**Comment by ItMeSarah** [comment]
> the dash doesnt disapear either

it does, just have to change servers for them to appear anywhere.
