### ISSUE TITLE
Dashes return after scrolling

### ISSUE THREAD

**Issue by cgolden15** [Niemiets/BD_Plugins#4]
## Kinda broken 
Major issue. Exactly as the title says, if you scroll down in the channel list and then return to the top, all the channels are loaded in with the dashes again. Demonstrated [here](https://www.youtube.com/watch?v=BPIwXxH1--o).

**Comment by Niemiets** [comment]
i'll fix it on sunday/monday because now i can't

**Comment by Niemiets** [comment]
it should be fixed https://raw.githubusercontent.com/Niemiets/BD_Plugins/68d1a952bc1c3ddcd95a1213f0a978137928604a/DashToSpaceInChannelName/DashToSpaceInChannelName.plugin.js
