### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by kittenvr** [Niemiets/BD_Plugins#9]
no worky

**Comment by hydargos123** [comment]
can confirm, plugin hasn't been working for me either

Canary 124397 (2bf79b5)
BetterDiscord 1.5.3
Host 1.0.46
Windows 11 64-Bit 22000.613

**Comment by hydargos123** [comment]
looks like the CSS class name things are simply out of date, at least on canary. I tried to fix them but it made a few things break (server header appearing like this on some servers) and didn't even fix it entirely, so I don't know
![image](https://user-images.githubusercontent.com/25777291/163683741-a8a4e99f-0ffe-4a46-9f4d-eac493169655.png)

**Comment by Justin14p** [comment]
What's your plugin version? Seems like the latest version (1.1.2) works just fine (at least on Discord Stable)

Stable 124397 (2bf79b5)
BetterDiscord 1.5.3
Host 1.0.9004
Windows 10 64-Bit (10.0.19042)

**Comment by kittenvr** [comment]
dunno

**Comment by Cleridwen** [comment]
1.1.2? my current version of DashToSpaceInChannelName is 0.0.6

**Comment by kittenvr** [comment]
i have version 0.0.6

**Comment by Justin14p** [comment]
Probably because this plugin couldn't update for some reasons

Make sure you download the latest version and replace with the old script:
https://github.com/Niemiets/BD_Plugins/blob/main/DashToSpaceInChannelName/DashToSpaceInChannelName.plugin.js

**Comment by Cleridwen** [comment]
ooh, indeed! version 0.0.6 didn't have an update link afaik. this works well now. thanks!

**Comment by Aidan-The-Dev** [comment]
This didn't seem to work for me :(
